### ISSUE TITLE
Doesn't work on Ubuntu 20.04 because "realpath" has no installation candidate

### ISSUE THREAD

**Issue by rbohuk** [activecm/shell-lib#4]
Can be fixed by adding `"$VERSION_CODENAME" = "focal"` to https://github.com/activecm/shell-lib/blob/master/acmlib.sh#L339 in addition to `"$VERSION_CODENAME" = "bionic"`

**Comment by william-stearns** [comment]
Fixed in pull request https://github.com/activecm/shell-lib/pull/11
